:toc:
:toclevels: 2
:sectnums:

= 第6回 応用情報技術者講義 データベース実践

筆者環境::
* Windows 10 Home 64bit / Windows 7 Professional Service Pack 1 32bit
* PostgreSQL 10.4
* Visual Studio 2017 Community

== CLIでデータベースを作ってみよう

なぜコマンドラインなのか？

. SQLに精通する目的
. CLIに慣れておいたほうがいざというとき役に立つ


=== データベースの作成

```SQL
CREATE DATABASE sample;
```

=== テーブルの作成

```SQL
CREATE TABLE workers
(worker_id CHAR(5) NOT NULL, 
worker_name VARCHAR(50) NOT NULL,
work_start_date DATE,
PRIMARY KEY (worker_id));　-- 文の最後に必ずセミコロンを置く
```

NOT NULL制約::
NULL（ヌル）は無記入の状態を表す。つまりNOT NULL制約とは、無記入を許可しないというルールのこと。

CHAR（キャラ）型::
固定長文字列。固定長より短い文字列を入力した場合、半角スペースで埋められる。

VARCHAR（バーキャラ）型::
可変長文字列。


TIP: SQLでは「--」を使うことでコメントを入力できる。複数行にまたがってコメントアウトしたい場合は、「/* */」を使う。

=== データの登録

```SQL
BEGIN TRANSACTION;

INSERT INTO workers VALUES ('00001', '佐藤太郎', '2008-08-15');
INSERT INTO workers VALUES ('00002', '鈴木仁', '2008-09-20');
INSERT INTO workers VALUES ('00003', '伊藤セニョリータ', '2015-03-12');

COMMIT;
```

== VB.NETからPostgreSQLデータベースに接続する

=== データベースとアプリケーションの関係

RDBへはSQLを使ってアクセスする。しかし、SQLとRDBのもつ機能だけでは複雑な処理（ビジネスロジック）に対応できない。

そこで、別のアプリケーションを作って、それ越しにデータベースに接続する方法がとられる。

image::svg/DBConnect.svg[DBConnect]

=== ロール

RDBMSに用意される、テーブルや関数に対する使用等の権限の設定。

ロールは複数のユーザーに割り当てることができる。

. スーパーユーザーでログイン
. ロールを追加する
. 追加したロールでデータベースにログイン
. SQLが実行できないことを確認する
. 再度スーパーユーザーでログイン
. GRANTでテーブルアクセス権限の付与

```SQL
CREATE ROLE role_sample WITH LOGIN PASSWORD 'password'; -- 2

psql -U role_sample -d sample　-- 3

SELECT * FROM workers; -- 4 権限がないため弾かれる

GRANT SELECT ON workers TO role_sample; -- 6
```

== LAN内のDBへアクセスする

LAN内でDBへアクセスする方法としては、まず2つ考えられる。

. DB自体を公開する（pg_hba.conf）
. DBへアクセスするアプリケーションを公開する（VB.NETのTcpListenerクラス等）

== LAN外からDBへアクセスする

LAN外からDBへリモートアクセスする方法としては、

. VPNを利用する（SoftEther Server等）
. リモートサーバーを立ち上げる（Apache, nginx等）

等が考えられる。

ここではVPNについて簡単に説明する。

=== VPN（Virtual Private Network）

一方のLANともう一方のLANの間にWANを通るトンネルを作る。
そのトンネルを通してLAN-LAN間のコンピュータと安全性の高い通信を行う仕組み。

=== SoftEther VPN

筑波大が開発したオープンソースのVPN構築ソフトウェア。

== セキュリティリスク

=== SQLインジェクション

サンプルではソースコードにSQLを直書きしているが、単純にこの中へユーザーからの入力を代入してしまうと、悪意ある入力に対応できなくなる。

入力文字列をエスケープしたり、あるいはORマッパー（npgsqlなど）のメソッドを使うなどの対処法が考えられる。


== お役立ちリンク

https://www.draw.io/[draw.io]::
色んな図を描画できるオープンソースのWebアプリ（ログイン不要）。この資料の画像はこれで描きました。desktop版もあるみたいです。

https://www.screentogif.com/[ScreenToGif]::
PC画面を簡単にGifアニメーションとしてキャプチャできる。オープンソース。前回の講義で使用しました。